version: '3.4'
services:

  mongooseim:
    container_name: schoolhub_mongooseim-1
    image: mongooseim/mongooseim
    hostname: mongooseim-1
    ports:
      - "5222:5222"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.2
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/member:/member
      - ./mongooseim/mnesia:/var/lib/mongooseim
      - ./mongooseim/cacert.pem:/usr/lib/mongooseim/priv/ssl/cacert.pem


  postgres:
    container_name: schoolhub_postgres
    image: postgres
    hostname: schoolhub
    command: -c ssl=off -c ssl_cert_file=/var/lib/postgresql/schoolhub.crt -c ssl_key_file=/var/lib/postgresql/schoolhub.key
    expose:
      - "5432"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.3
    restart: always
    shm_size: 256M
    volumes:
      - ./postgres/schema:/docker-entrypoint-initdb.d
      - ./postgres/ssl/schoolhub.crt:/var/lib/postgresql/schoolhub.crt
      - ./postgres/ssl/schoolhub.key:/var/lib/postgresql/schoolhub.key
    environment:
      - POSTGRES_PASSWORD=schoolhub
      - POSTGRES_USER=schoolhub


  client_dist_tester:
    container_name: schoolhub_client_test
    image: elixir
    hostname: schoolhub_client
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.10
    restart: always
    tty: true
    volumes:
      - ./schoolhub_client:/root/schoolhub_client
      - ./test:/root/test
    environment:
      - ERLANG_COOKIE=test_cookie
      - NODES_AMOUNT=5
    entrypoint: /root/test/dist_entrypoint.sh
      
    
networks:
  schoolhub_network:
    ipam:
      config:
        - subnet: 10.3.0.0/16
        
