version: '3.4'
services:

  mongooseim-1:
    container_name: mongooseim-1
    image: mongooseim/mongooseim:PR-2860
    hostname: mongooseim-1
    expose:
      - "5222"
      - "5269"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.2.1
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/member:/member
      - ./ssl:/usr/lib/mongooseim/priv/ssl

  mongooseim-2:
    container_name: mongooseim-2
    image: mongooseim/mongooseim:PR-2860
    hostname: mongooseim-2
    expose:
      - "5222"
      - "5269"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.2.2
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/member:/member
      - ./ssl:/usr/lib/mongooseim/priv/ssl

  
  postgres:
    container_name: schoolhub_postgres
    image: postgres
    hostname: schoolhub
    expose:
      - "5432"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.3
    restart: always
    shm_size: 256M
    volumes:
      - ./postgres/schema/pg.sql:/docker-entrypoint-initdb.d/pg.sql
      - ./ssl/schoolhub.crt:/var/lib/postgresql/schoolhub.crt
      - ./ssl/schoolhub.key:/var/lib/postgresql/schoolhub.key
    environment:
      - POSTGRES_PASSWORD=schoolhub
      - POSTGRES_USER=schoolhub
    command: -c ssl=on
             -c ssl_cert_file=/var/lib/postgresql/schoolhub.crt
             -c ssl_key_file=/var/lib/postgresql/schoolhub.key


  haproxy:
    container_name: schoolhub_haproxy
    image: haproxy
    hostname: schoolhub
    expose:
      - "8080"
      - "8404"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.4
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./ssl/schoolhub.pem:/etc/cert/schoolhub.pem
      - ./ssl/schoolhub_cacert.crt:/etc/cert/schoolhub_cacert.pem
      
    
networks:
  schoolhub_network:
    ipam:
      config:
        - subnet: 10.3.0.0/16
        
