version: '3.4'
services:

  mongooseim-1:
    container_name: mongooseim-1
    image: mongooseim/mongooseim:3.7.1
    hostname: mongooseim-1
    expose:
      - "5222"
      - "5269"
      - "5280"
      - "5285"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.2.1
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/member:/member
      - ./letsencrypt/live/schoolhub.com:/usr/lib/mongooseim/priv/ssl
    environment:
      - MONGOOSEIM_CONFIG_FORMAT=cfg

  mongooseim-2:
    container_name: mongooseim-2
    image: mongooseim/mongooseim:3.7.1
    hostname: mongooseim-2
    expose:
      - "5222"
      - "5269"
      - "5280"
      - "5285"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.2.2
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/member:/member
      - ./letsencrypt/live/schoolhub.com:/usr/lib/mongooseim/priv/ssl
    environment:
      - MONGOOSEIM_CONFIG_FORMAT=cfg

  
  postgres:
    container_name: schoolhub_postgres
    image: postgres
    hostname: schoolhub.com
    expose:
      - "5432"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.3
    restart: always
    shm_size: 256M
    volumes:
      - ./postgres/schema/pg.sql:/docker-entrypoint-initdb.d/pg.sql
      - ./letsencrypt/live/schoolhub.com/fullchain.pem:/var/lib/postgresql/schoolhub.crt
      - ./letsencrypt/live/schoolhub.com/privkey.pem:/var/lib/postgresql/schoolhub.key
    environment:
      - POSTGRES_PASSWORD=schoolhub
      - POSTGRES_USER=schoolhub
    command: -c ssl=on
             -c ssl_cert_file=/var/lib/postgresql/schoolhub.crt
             -c ssl_key_file=/var/lib/postgresql/schoolhub.key


  haproxy:
    container_name: schoolhub_haproxy
    image: haproxy
    hostname: schoolhub.com
    expose:
      - "8404"
    ports:
      - "80:80"
      - "443:443"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.4
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./letsencrypt/live/schoolhub.com/schoolhub.com.pem:/etc/cert/schoolhub.com.pem
      - ./letsencrypt/live/schoolhub.com/chain.pem:/etc/cert/chain.pem


  phx_server:
    container_name: phx_server
    image: phx_server:v0.2
    hostname: schoolhub.com
    build:
      context: ./schoolhub
    expose:
      - "4000"
      - "4001"
    networks:
      schoolhub_network:
        ipv4_address: 10.3.0.5
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./schoolhub/lib:/opt/app/lib
      - ./letsencrypt/live/schoolhub.com:/opt/app/priv/cert
    environment:
      - PGUSER=schoolhub
      - PGHOST=10.3.0.3
      - DATABASE_URL=ecto://schoolhub:schoolhub@10.3.0.3/schoolhub
      - SECRET_KEY_BASE=/d8p4MwXOA3uA9jZ2fIouO5BwvwOIRM9Gqny3Cf7XFaY/pQ1Yukf53H9iy9AugqP
      - MIX_ENV=prod
      
    
networks:
  schoolhub_network:
    ipam:
      config:
        - subnet: 10.3.0.0/16
        
