version: '3.4'
services:

  mongooseim-1:
    container_name: mongooseim-1
    image: mongooseim/mongooseim:3.7.1
    hostname: mongooseim-1
    expose:
      - "5222"
      - "5269"
      - "5280"
      - "5285"
    networks:
      - schoolhub_network
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./mongooseim/entrypoint.sh:/entrypoint.sh
      - ./mongooseim/member:/config_temp
      - ./letsencrypt/selfsigned/$DOMAIN/certs:/usr/lib/mongooseim/priv/ssl
    entrypoint: /entrypoint.sh
    environment:
      - MONGOOSEIM_CONFIG_FORMAT=cfg
      - JOIN_CLUSTER=false
      - DOMAIN=$DOMAIN
    env_file:
      - ./postgres/postgres_single.env


  postfix:
    container_name: schoolhub_postfix
    image: boky/postfix:v3.3.0
    hostname: postfix
    ports:
      - "1587:587"
    networks:
      - schoolhub_network
    restart: always
    volumes:
      - ./letsencrypt/DKIM:/etc/opendkim/keys
    environment:
      - ALLOWED_SENDER_DOMAINS=$DOMAIN localhost
      - DKIM_AUTOGENERATE=true
      - INBOUND_DEBUGGING=

  
  postgres:
    container_name: schoolhub_postgres
    image: postgres:13.3
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - schoolhub_network
    restart: always
    shm_size: 256M
    volumes:
      - ./postgres/schema/pg.sql:/docker-entrypoint-initdb.d/pg.sql
      - ./letsencrypt/selfsigned/$DOMAIN/certs/fullchain.pem:/etc/postgresql/ssl/fullchain.pem
      - ./letsencrypt/selfsigned/$DOMAIN/certs/privkey.pem:/etc/postgresql/ssl/privkey.pem
      - ./postgres/data/data:/var/lib/postgresql/data
    env_file:
      - ./postgres/postgres_single.env
    command: -c ssl=on
             -c ssl_cert_file=/etc/postgresql/ssl/fullchain.pem
             -c ssl_key_file=/etc/postgresql/ssl/privkey.pem


  haproxy:
    container_name: schoolhub_haproxy
    image: haproxy:2.4
    hostname: haproxy
    expose:
      - "8404"
    ports:
      - "80:1080"
      - "443:1443"
      - "5280:1280"
      - "5285:1285"
      - "8404:1404"
    networks:
      - schoolhub_network
    restart: always
    volumes:
      - ./haproxy/haproxy_single.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./letsencrypt/live/$DOMAIN/certs/joined_cert.pem:/etc/cert/live/joined_cert.pem
      - ./letsencrypt/selfsigned/$DOMAIN/certs/chain.pem:/etc/cert/selfsigned/chain.pem


  phx-server:
    container_name: phx-server
    image: phx_server:v0.3
    hostname: phx-server
    build:
      context: ./schoolhub
    expose:
      - "4000"
      - "4001"
    networks:
      - schoolhub_network
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./schoolhub/lib:/opt/app/lib
      - ./letsencrypt/selfsigned/$DOMAIN/certs:/opt/app/priv/cert
    environment:
      - MIX_ENV=prod
      - DOMAIN=$DOMAIN
      - EMAIL_USE_API=true
      - MAILJET_CREDS="dummy:dummy"
    env_file:
      - ./postgres/postgres_single.env
      
    
networks:
  schoolhub_network:
    
