apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kubernetes/headless/postgres.yaml
  - ./kubernetes/headless/router_phoenix.yaml
  - ./kubernetes/headless/postfix.yaml
  - ./kubernetes/headless/haproxy.yaml
  - ./kubernetes/headless/pg_data_pv.yaml
  - ./kubernetes/headless/storage.yaml
  - ./kubernetes/headless/schoolhub.yaml

configMapGenerator:
  - name: domain-address
    envs:
      - ./.env
  - name: postgres-schema
    files:
      - ./postgres/schema/pg.sql
  - name: haproxy-config
    files:
      - ./haproxy/haproxy_instance.cfg
  - name: haproxy-router-config
    files:
      - ./haproxy/haproxy_router.cfg
  - name: mongooseim-config
    files:
      - ./mongooseim/member/mongooseim.cfg
      - ./mongooseim/member/app.config
      - ./mongooseim/member/vm.args
      - ./mongooseim/member/vm.dist.args
  - name: mongooseim-entrypoint
    files:
      - ./mongooseim/entrypoint.sh

secretGenerator:
  - name: postgres-creds
    envs:
      - ./postgres/postgres.env
  - name: postgres-router-creds
    envs:
      - ./postgres/postgres_router.env
  - name: tls-selfsigned-secret
    files:
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/chain.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/cert.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/fullchain.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/privkey.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/joined_cert.pem
  - name: tls-letsencrypt-secret
    files:
      - ./letsencrypt/live/schoolhub.ddns.net/certs/joined_cert.pem
  - name: admin-password
    files:
      - ./schoolhub/priv/repo/admin_pw.secret
