apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kubernetes/deployment/postgres.yaml
  - ./kubernetes/deployment/mongooseim.yaml
  - ./kubernetes/deployment/phoenix.yaml
  - ./kubernetes/deployment/postfix.yaml
  - ./kubernetes/deployment/haproxy.yaml
  - ./kubernetes/deployment/pg_data_pv.yaml

configMapGenerator:
  - name: domain-address
    envs:
      - ./.env
  - name: postgres-schema
    files:
      - ./postgres/schema/pg.sql
  - name: haproxy-config
    files:
      - ./haproxy/haproxy.cfg
  - name: mongooseim-config
    files:
      - ./mongooseim/member/mongooseim.cfg
      - ./mongooseim/member/app.config
      - ./mongooseim/member/vm.args
      - ./mongooseim/member/vm.dist.args
  - name: mongooseim-entrypoint
    files:
      - ./mongooseim/entrypoint.sh

secretGenerator:
  - name: postgres-creds
    envs:
      - ./postgres/postgres.env
  - name: tls-selfsigned-secret
    files:
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/chain.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/cert.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/fullchain.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/privkey.pem
      - ./letsencrypt/selfsigned/schoolhub.ddns.net/certs/joined_cert.pem
  - name: tls-letsencrypt-secret
    files:
      - ./letsencrypt/live/schoolhub.ddns.net/certs/joined_cert.pem
