apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  ports:
  - name: 1587-587
    nodePort: 30587
    port: 1587
    protocol: TCP
    targetPort: 587
  selector:
    app: postfix
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolhub-postfix
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: schoolhub-postfix
        image: boky/postfix
        env:
        - name: ALLOWED_SENDER_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: domain-address
              key: DOMAIN
        - name: DKIM_AUTOGENERATE
          value: "true"
        - name: INBOUND_DEBUGGING
          value: ""
        ports:
        - containerPort: 587
          name: smtp
