apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  ports:
  - name: 2049-tcp
    port: 2049
    protocol: TCP
  - name: 111-tcp
    port: 111
    protocol: TCP
  - name: 20048-tcp
    port: 20048
    protocol: TCP
  - name: 2049-udp
    port: 2049
    protocol: UDP
  - name: 111-udp
    port: 111
    protocol: UDP
  - name: 20048-udp
    port: 20048
    protocol: UDP
  selector:
    app: nfs-server
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: cpuguy83/nfs-server
        env:
        - name: SHARED_DIRECTORY
          value: /exports
        ports:
        - containerPort: 2049
          name: nfs-tcp
          protocol: TCP
        - containerPort: 2049
          name: nfs-udp
          protocol: UDP
        - containerPort: 111
          name: rpcbind-tcp
          protocol: TCP
        - containerPort: 111
          name: rpcbind-udp
          protocol: UDP
        - containerPort: 20048
          name: mountd-tcp
          protocol: TCP
        - containerPort: 20048
          name: mountd-udp
          protocol: UDP
        #volumeMounts:
        #- name: nfs-data-pv
        #  mountPath: /exports
        securityContext:
          privileged: true
        args: ["/exports"]
      #volumes:
      #- name: nfs-data-pv
      #  persistentVolumeClaim:
      #    claimName: nfs-pvc
