apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  ports:
  - name: 2049-2049
    nodePort: 32049
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    app: nfs-server
  type: NodePort
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: moundt
        - containerPort: 111
          name: rpcbind
        volumeMounts:
        - name: nfs-data-pv
          mountPath: /nfsshare
        securityContext:
          privileged: true
      volumes:
      - name: nfs-data-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
