apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100M
  storageClassName: local-path
  hostPath:
    path: /volumes_data/postgres/data/router_data
    type: DirectoryOrCreate
