apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  ports:
  - name: 1587-587
    port: 1587
    targetPort: 587
  - name: 25-25
    port: 25
    targetPort: 25
  selector:
    app: postfix

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolhub-router-postfix
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: schoolhub-router-postfix
        image: boky/postfix:v3.3.0
        env:
        - name: ALLOWED_SENDER_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: domain-address
              key: DOMAIN
        - name: DKIM_AUTOGENERATE
          value: "true"
        - name: INBOUND_DEBUGGING
          value: ""
        ports:
        - containerPort: 587
          name: smtp
        - containerPort: 25
          name: smtp-relay
