apiVersion: v1
kind: Service
metadata:
  name: phx-server
  labels:
    app: phx-server
spec:
  ports:
  - name: 4000-4000
    port: 4000
    targetPort: 4000
  - name: 4001-4001
    port: 4001
    targetPort: 4001
  selector:
    app: phx-server

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-creator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-scale-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["create", "patch", "update", "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-scale-rb
subjects:
  - kind: ServiceAccount
    name: instance-creator
roleRef:
  kind: Role
  name: statefulset-scale-role
  apiGroup: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolhub-router-phoenix
  labels:
    app: phx-server
spec:
  selector:
    matchLabels:
      app: phx-server
  template:
    metadata:
      labels:
        app: phx-server
    spec:
      serviceAccountName: instance-creator
      containers:
      - name: schoolhub-router-phoenix
        image: router_phx_server:v0.1.0
        env:
        - name: MIX_ENV
          value: prod
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: domain-address
              key: DOMAIN
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-router-creds
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-router-creds
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-router-creds
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-router-creds
              key: POSTGRES_HOST
        ports:
        - containerPort: 4000
          name: http
        - containerPort: 4001
          name: https
        volumeMounts:
        - name: tls-secret
          mountPath: /opt/app/priv/cert/
      volumes:
      - name: tls-secret
        secret:
          secretName: tls-selfsigned-secret
          items:
          - key: fullchain.pem
            path: fullchain.pem
          - key: privkey.pem
            path: privkey.pem
          - key: chain.pem
            path: chain.pem
