apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - name: 5432-5432
    nodePort: 30432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolhub-postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: schoolhub-postgres
        image: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pg-schema
          mountPath: /docker-entrypoint-initdb.d/pg.sql
          readOnly: true
        - name: tls-secret-modified
          mountPath: /etc/postgresql/ssl/
        args: ["-c", "ssl=on",
               "-c", "ssl_cert_file=/etc/postgresql/ssl/fullchain.pem",
               "-c", "ssl_key_file=/etc/postgresql/ssl/privkey.pem"]
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c"]
        args: ["cp /secret/* /etc/postgresql/ssl/;
                chown -R 999:999 /etc/postgresql/ssl/privkey.pem"]
        volumeMounts:
        - name: tls-secret
          mountPath: /secret/
        - name: tls-secret-modified
          mountPath: /etc/postgresql/ssl/
      volumes:
      - name: pg-schema
        hostPath:
          path: /volumes_data/postgres/schema/pg.sql
          type: File
      - name: tls-secret
        secret:
          secretName: tls-selfsigned-secret
          items:
          - key: fullcert
            path: fullchain.pem
          - key: key
            path: privkey.pem
            mode: 0600
      - name: tls-secret-modified
        emptyDir: {}
